pretrain: '/home/user/Documents/zzx/ActionCLIP/vit-b-16-8f.pt'
# '/home/user/Documents/zzx/ActionCLIP/exp/clip_ucf/ViT-B/16/ucf101/model_best.pt'
# '/home/user/Documents/zzx/ActionCLIP/vit-32-8f.pt'
# '/home/user/Documents/zzx/ActionCLIP/vit-b-16-8f.pt'
seed: 1024
data:
    dataset: HRI10
    modality: RGB
    num_segments: 8
    seg_length: 1
    split: 1
    batch_size: 1
    workers: 8
    gpus: 1
    num_classes: 10
    k_shot: 8
    augment_epoch : 10
    image_tmpl: 'img_{:05d}.jpg'
    train_list: '/home/user/Documents/zzx/ActionCLIP/lists/HRI10/train_rgb_split1_8shot.txt'
    val_list: '/home/user/Documents/zzx/ActionCLIP/lists/HRI10/val_rgb_split1.txt'
    label_list: 'lists/HRI10.csv'
    index_bias: 1
    input_size: 224
    randaug:
        N: 0 #2
        M: 0  #9
network:
    arch: ViT-B/16  #ViT-B/32 ViT-B/16
    init: True 
    drop_out: 0.0 
    emb_dropout: 0.0 
    type: clip_ucf
    sim_header: "Transf"   #Transf   meanP  LSTM Conv_1D Transf_cls
    fix_text: False
    fix_img: False
    describe:
solver:
    type: cosine
    epochs: 50
    start_epoch: 0
    epoch_offset: 0
    optim: adamw
    lr: 5.e-6
    lr_warmup_step: 5
    momentum: 0.9
    weight_decay: 0.2
    lr_decay_step: 15
    lr_decay_factor: 0.1
    clip_gradient: 20
    loss_type: nll
    evaluate: False
    ratio: 1
    f_ratio: 10
logging:
    print_freq: 10
    eval_freq: 1
